default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/wordle") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
